---
title: "PLIER pathways found after doubling sample size"
output: html_notebook
---

Brief explanation

```{r}
library(tidyverse)
library(PLIER)

data(bloodCellMarkersIRISDMAP)
data(canonicalPathways)
data(oncogenicPathways)
data(svmMarkers)
```

```{r}
brca_pathways_df <- read_tsv("plots/data/BRCA_subtype_PLIER_pathways.tsv") %>%
  mutate(cancer_type = "BRCA")
gbm_pathways_df <- read_tsv("plots/data/GBM_subtype_PLIER_pathways.tsv") %>%
  mutate(cancer_type = "GBM")

meaningful_difference <- 0.2
```

```{r}

bind_rows(brca_pathways_df, gbm_pathways_df) %>%
  filter(FDR < 0.05) %>%
  group_by(nmeth, pseq, pathway, cancer_type) %>%
  summarize(n_seeds = length(unique(seed_index)),
            prop_seeds = n_seeds/10,
            .groups = "drop") %>%
  mutate(nmeth = str_replace(nmeth, " ", "_")) %>%
  mutate(nmeth = str_replace(nmeth, "-", "_")) %>%
  mutate(nmeth = str_remove_all(nmeth, "\\(")) %>%
  mutate(nmeth = str_remove_all(nmeth, "\\)")) %>%
  mutate(nmeth_pseq = str_c(nmeth, pseq, sep = "_")) %>%
  select(cancer_type, pathway, prop_seeds, nmeth_pseq) %>%
  pivot_wider(id_cols = c("cancer_type", "pathway"),
              names_from = nmeth_pseq,
              values_from = prop_seeds) %>%
  mutate_if(is.numeric, replace_na, 0) %>%
  filter(log_0 - array_only_50 >= .2,
         log_100 - seq_only_50 >= .2,
         log_0 > 0.5,
         log_100 > 0.5,
         npn_50 > 0.5) %>%
  select(cancer_type, pathway, array_only_50, seq_only_50, log_0, log_100, npn_50) %>%
  filter(pathway %in% colnames(oncogenicPathways)) %>%
  arrange(cancer_type) %>%
  knitr::kable()
```
